"""
Django settings for ghanahomes project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

import os
from dotenv import load_dotenv

# Load environment variables from .env (development convenience)
load_dotenv(str(BASE_DIR / '.env'))

# Initialize Sentry for error tracking (optional)
try:
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration

    SENTRY_DSN = os.getenv('SENTRY_DSN', '')
    if SENTRY_DSN:
        sentry_sdk.init(
            dsn=SENTRY_DSN,
            integrations=[DjangoIntegration()],
            traces_sample_rate=0.1,  # 10% sample rate for performance monitoring
            send_default_pii=False,  # Don't send PII by default
            environment=os.getenv('ENVIRONMENT', 'development')
        )
except Exception:
    # Sentry is optional in development; continue without it if not installed/configured
    sentry_sdk = None

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-s8k!jl^p*124=y@s#z0kf9+p%d45y_p7ry-14kz=k&%n^)iq!1')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = [
    'ghhomes.pythonanywhere.com',
    'www.ghhomes.pythonanywhere.com',
    'localhost',
    '127.0.0.1',
]

# Optional: populate sensitive settings from environment
GOOGLE_MAPS_API_KEY = os.getenv('GOOGLE_MAPS_API_KEY', '')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Project apps
    'accounts',
    'chat',
    'properties',
    'payments',
    'subscriptions',
    # 'django_q',  # Temporarily disabled - install with: pip install django-q==1.3.9
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'accounts.audit_middleware.AuditLoggingMiddleware',
    'ghanahomes.error_handling.ErrorHandlingMiddleware',  # Error handling
]

# Security settings
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_SECURITY_POLICY = {
    'default-src': ("'self'",),
    'script-src': ("'self'", "'unsafe-inline'", 'cdn.jsdelivr.net'),
    'style-src': ("'self'", "'unsafe-inline'", 'cdn.jsdelivr.net', 'fonts.googleapis.com'),
    'font-src': ("'self'", 'fonts.googleapis.com', 'fonts.gstatic.com'),
    'img-src': ("'self'", 'data:', 'https:'),
}
X_FRAME_OPTIONS = 'DENY'

# CSRF and CORS settings for ghhomes.pythonanywhere.com
CSRF_TRUSTED_ORIGINS = [
    'https://ghhomes.pythonanywhere.com',
    'https://www.ghhomes.pythonanywhere.com',
]

# SSL/TLS Settings (for production)
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True  # Prevent JavaScript access to session cookie
    CSRF_COOKIE_HTTPONLY = True     # Prevent JavaScript access to CSRF cookie
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

ROOT_URLCONF = 'ghanahomes.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'ghanahomes.context_processors.google_maps_api_key',
                    'ghanahomes.context_processors.paystack_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'ghanahomes.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'


# Tell Django where to find additional static files and media uploaded by users
STATICFILES_DIRS = [BASE_DIR / 'static']

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Use the custom user model from the accounts app
AUTH_USER_MODEL = 'accounts.User'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Paystack Settings (load from environment for safety)
PAYSTACK_SECRET_KEY = os.getenv('PAYSTACK_SECRET_KEY', '')
PAYSTACK_PUBLIC_KEY = os.getenv('PAYSTACK_PUBLIC_KEY', '')

# Location Field Settings (for django-location-field package)
LOCATION_FIELD = {
    'provider.google.APIKEY': os.getenv('GOOGLE_MAPS_API_KEY', ''),
}

# Email Settings
# Default to console backend for safe development, but enable SMTP when credentials are provided
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'console')
if EMAIL_BACKEND == 'console':
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
elif EMAIL_BACKEND == 'smtp':
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# SMTP settings (picked up from .env when available)
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', 'False') == 'True'

DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'realhuntsmen.tech@gmail.com')
# Official contact details
OFFICIAL_EMAIL = 'realhuntsmen.tech@gmail.com'
OFFICIAL_PHONE = '+233 55 606 7555'
# Public site URL used in emails
SITE_URL = os.getenv('SITE_URL', 'https://ghhomes.pythonanywhere.com')

# Django Channels
ASGI_APPLICATION = 'ghanahomes.asgi.application'
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('127.0.0.1', 6379)],
        },
    },
}

# Ghana Regions for forms
GHANA_REGIONS = [
    ('greater-accra', 'Greater Accra'),
    ('ashanti', 'Ashanti'),
    ('western', 'Western'),
    ('eastern', 'Eastern'),
    ('central', 'Central'),
    ('northern', 'Northern'),
    ('upper-east', 'Upper East'),
    ('upper-west', 'Upper West'),
    ('volta', 'Volta'),
    ('bono', 'Bono'),
    ('bono-east', 'Bono East'),
    ('ahafo', 'Ahafo'),
    ('savannah', 'Savannah'),
    ('north-east', 'North East'),
    ('oti', 'Oti'),
    ('western-north', 'Western North'),
]

# Login/Logout URLs
LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = 'accounts:dashboard'
LOGOUT_REDIRECT_URL = 'home'

# Cache Configuration
# Use Redis for caching if available, otherwise fall back to local memory
if os.getenv('REDIS_URL'):
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': os.getenv('REDIS_URL', 'redis://127.0.0.1:6379/1'),
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'ghanahomes-cache',
            'TIMEOUT': 300,  # 5 minutes default timeout
            'OPTIONS': {
                'MAX_ENTRIES': 1000
            }
        }
    }

# Cache timeout for specific views
CACHE_TIMEOUTS = {
    'property_list': 600,        # 10 minutes
    'property_detail': 1800,     # 30 minutes
    'home_page': 300,            # 5 minutes
    'categories': 3600,          # 1 hour
}

# Django Q Configuration
Q_CLUSTER = {
    'name': 'ghanahomes',
    'workers': 1,  # Single worker more stable on Windows
    'recycle': 500,
    'timeout': 60,
    'compress': True,
    'save_limit': 250,
    'queue_limit': 500,
    'sync': False,  # Use async processing
    'label': 'Django Q',
    # Use Django ORM as the broker (works without Redis). Change to 'redis' config if
    # you have Redis available at 127.0.0.1:6379.
    'orm': 'default',
    'catch_up': False,  # Don't try to catch up on missed tasks
    'scheduler': True,  # Enable scheduler for periodic tasks
    'scheduled': [
        {
            'func': 'payments.tasks.check_and_retry_timed_out_payments',
            'schedule': 'minutes',
            'repeats': -1,  # Run indefinitely
            'minutes': 5,  # Run every 5 minutes
        }
    ]
}

# Django Debug Toolbar
INTERNAL_IPS = ['127.0.0.1', 'localhost', '::1']
DEBUG_TOOLBAR_CONFIG = {
    'SHOW_TOOLBAR_CALLBACK': lambda r: DEBUG,
    'SHOW_TEMPLATE_CONTEXT': True,
    'ENABLE_STACKTRACES': True,
    'SQL_WARNING_THRESHOLD': 500,  # ms
}

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {message}',
            'style': '{',
        },
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'ghanahomes.log'),
            'maxBytes': 1024 * 1024 * 10,  # 10 MB
            'backupCount': 10,
            'formatter': 'verbose',
        },
        'error_file': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'errors.log'),
            'maxBytes': 1024 * 1024 * 10,  # 10 MB
            'backupCount': 10,
            'formatter': 'verbose',
        },
        'audit_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'audit.log'),
            'maxBytes': 1024 * 1024 * 10,  # 10 MB
            'backupCount': 10,
            'formatter': 'verbose',
        },
        'payments_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'payments.log'),
            'maxBytes': 1024 * 1024 * 10,  # 10 MB
            'backupCount': 10,
            'formatter': 'verbose',
        },
        'mail_admins': {
            'level': 'ERROR',
            'filters': ['require_debug_false'],
            'class': 'django.utils.log.AdminEmailHandler',
            'include_html': True,
        }
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['error_file', 'mail_admins'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.security': {
            'handlers': ['error_file'],
            'level': 'WARNING',
            'propagate': False,
        },
        'accounts': {
            'handlers': ['console', 'audit_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'payments': {
            'handlers': ['console', 'payments_file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'properties': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'subscriptions': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'chat': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
    }
}

# Create logs directory if it doesn't exist
LOG_DIR = os.path.join(BASE_DIR, 'logs')
if not os.path.exists(LOG_DIR):
    os.makedirs(LOG_DIR)
# Admin Notification Email Settings
# Configure which admins receive notifications
ADMIN_NOTIFICATION_EMAILS = [
    os.getenv('ADMIN_EMAIL', 'realhuntsmen.tech@gmail.com'),
]

# What notifications to send to admins
ADMIN_NOTIFICATIONS = {
    'verification_submitted': True,      # When user submits verification
    'verification_approved': True,       # When verification is approved
    'verification_declined': True,       # When verification is declined
    'property_listed': True,             # When property is listed
    'new_inquiry': True,                 # When new inquiry received
    'payment_completed': True,           # When payment completes
    'payment_failed': True,              # When payment fails
    'subscription_created': True,        # When subscription created
    'subscription_expired': True,        # When subscription expires
    'user_registered': True,             # When new user registers
    'high_value_payment': True,          # When payment > threshold
}

# Payment amount threshold for admin notification (in GHS)
PAYMENT_NOTIFICATION_THRESHOLD = 1000.00