# Generated by Django 4.2.25 on 2025-12-18 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['tenant', '-updated_at'], name='chat_chatro_tenant__5679b7_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['landlord', '-updated_at'], name='chat_chatro_landlor_b6ce35_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['property'], name='chat_chatro_propert_49cd6d_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat_room', '-created_at'], name='chat_messag_chat_ro_16abb8_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_read', '-created_at'], name='chat_messag_is_read_2ac7c8_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender'], name='chat_messag_sender__c4389c_idx'),
        ),
    ]
