# Generated by Django 4.2.25 on 2025-12-18 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_propertyedithistory_paymentaudit_loginhistory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentaudit',
            name='new_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='paymentaudit',
            name='old_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
