# Generated by Django 4.2.25 on 2025-11-05 01:46

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='location',
            field=location_field.models.plain.PlainLocationField(default='5.6037,-0.1870', max_length=63),
        ),
    ]
