# Generated by Django 4.2.25 on 2025-12-14 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_property_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.CharField(default='5.6037,-0.1870', max_length=50),
        ),
    ]
