# Generated by Django 4.2.25 on 2025-12-18 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_property_location'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['user', '-created_at'], name='properties__user_id_172cc5_idx'),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['property', '-created_at'], name='properties__propert_0bccc9_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['owner', 'status'], name='properties__owner_i_30ec29_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['region', 'status'], name='properties__region_0d3801_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['status', '-created_at'], name='properties__status_5b95bb_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['is_featured', '-created_at'], name='properties__is_feat_7e5c2a_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['price', 'status'], name='properties__price_968017_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['category', 'status'], name='properties__categor_a89819_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyimage',
            index=models.Index(fields=['property', '-uploaded_at'], name='properties__propert_adf102_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyimage',
            index=models.Index(fields=['property', 'is_primary'], name='properties__propert_6e4e30_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyreview',
            index=models.Index(fields=['property', '-created_at'], name='properties__propert_ee1663_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyreview',
            index=models.Index(fields=['user', '-created_at'], name='properties__user_id_ad89d3_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyreview',
            index=models.Index(fields=['rating'], name='properties__rating_8306d4_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyview',
            index=models.Index(fields=['property', '-viewed_at'], name='properties__propert_557023_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyview',
            index=models.Index(fields=['user', '-viewed_at'], name='properties__user_id_447880_idx'),
        ),
    ]
