# Generated by Django 5.2.8 on 2026-01-27 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_favorite_properties__user_id_172cc5_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='currency',
            field=models.CharField(choices=[('GHS', 'Ghana Cedis (GHS)'), ('USD', 'US Dollar (USD)'), ('EUR', 'Euro (EUR)')], default='GHS', max_length=3),
        ),
        migrations.AlterField(
            model_name='property',
            name='region',
            field=models.CharField(choices=[('greater-accra', 'Greater Accra'), ('ashanti', 'Ashanti'), ('western', 'Western'), ('eastern', 'Eastern'), ('central', 'Central'), ('northern', 'Northern'), ('upper-east', 'Upper East'), ('upper-west', 'Upper West'), ('volta', 'Volta'), ('bono', 'Bono'), ('bono-east', 'Bono East'), ('ahafo', 'Ahafo'), ('savannah', 'Savannah'), ('north-east', 'North East'), ('oti', 'Oti'), ('western-north', 'Western North')], max_length=100),
        ),
    ]
