# Generated by Django 5.2.8 on 2026-01-31 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_alter_property_currency_alter_property_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Property Types',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('villa', 'Villa'), ('duplex', 'Duplex'), ('studio', 'Studio'), ('commercial', 'Commercial'), ('office', 'Office Space'), ('shop', 'Shop'), ('warehouse', 'Warehouse'), ('land', 'Land'), ('townhouse', 'Townhouse'), ('bungalow', 'Bungalow'), ('penthouse', 'Penthouse'), ('room', 'Room/Bedsit'), ('guest-house', 'Guest House'), ('shared-apartment', 'Shared Apartment')], max_length=20),
        ),
    ]
